import { MessageBubble } from "./MessageBubble";

/**
 * Entry-moment insight bubble — Day 13 (DESIGN.md §6.2, UX frame 15).
 *
 * Rendered below a committed parse card when `POST /transactions/confirm`
 * returns a non-null `insight`. The sentence is generated by the
 * deterministic rule engine in `app/services/entry_moment.py`; this
 * component only displays it.
 *
 * No buttons, no dismiss × — rate limits handle fatigue server-side.
 * Spec is firm: never a modal, never a toast.
 */
export function EntryInsightBubble({ text }: { text: string }) {
  return (
    <div className="flex w-full justify-start animate-slide-up-in">
      <MessageBubble
        role="assistant"
        bubble
        className="italic text-ink-secondary"
      >
        {text}
      </MessageBubble>
    </div>
  );
}
